// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCoBqbadaHdAfoztSqUp_P1hjE2c8PIwk',
    appId: '1:705478736954:web:0eba407b872efaf2208903',
    messagingSenderId: '705478736954',
    projectId: 'flickrate-b668e',
    authDomain: 'flickrate-b668e.firebaseapp.com',
    storageBucket: 'flickrate-b668e.appspot.com',
    measurementId: 'G-009F7SVW5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEn0B0eQU5Uzu7Itb6jD-BFwPvP_tC9_c',
    appId: '1:705478736954:android:a57e7f020637f443208903',
    messagingSenderId: '705478736954',
    projectId: 'flickrate-b668e',
    storageBucket: 'flickrate-b668e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwU5NwDJQY2kl9fO6wfH6FHHaY71zxbXg',
    appId: '1:705478736954:ios:add316a232796df9208903',
    messagingSenderId: '705478736954',
    projectId: 'flickrate-b668e',
    storageBucket: 'flickrate-b668e.appspot.com',
    androidClientId: '705478736954-l810tgdegl7bb8ndp8s07n4m6s3tdo3n.apps.googleusercontent.com',
    iosClientId: '705478736954-lr24f7h10vn3ddkpvb7g44ureaecka5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flickrate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwU5NwDJQY2kl9fO6wfH6FHHaY71zxbXg',
    appId: '1:705478736954:ios:add316a232796df9208903',
    messagingSenderId: '705478736954',
    projectId: 'flickrate-b668e',
    storageBucket: 'flickrate-b668e.appspot.com',
    androidClientId: '705478736954-l810tgdegl7bb8ndp8s07n4m6s3tdo3n.apps.googleusercontent.com',
    iosClientId: '705478736954-lr24f7h10vn3ddkpvb7g44ureaecka5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flickrate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCoBqbadaHdAfoztSqUp_P1hjE2c8PIwk',
    appId: '1:705478736954:web:c1d717d5ae36732b208903',
    messagingSenderId: '705478736954',
    projectId: 'flickrate-b668e',
    authDomain: 'flickrate-b668e.firebaseapp.com',
    storageBucket: 'flickrate-b668e.appspot.com',
    measurementId: 'G-61C1LP8V50',
  );
}
